services:
  vending_postgres:
    image: postgres:latest
    container_name: vending_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vending_machine
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db-networks
  rust-app:
    depends_on:
      - vending_postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    networks:
      - db-networks

networks:
  db-networks:

volumes:
  postgres_data:
